---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgBM4bvFLdThXz9XtQPVYXaYjcVOTbawtvQi4imGzsfo2ux7uNL6CJWPmjCBXA/QBBhL4bS4+jHmf2G8lobu1XIUKdBhaVUEIvw3OWEWPTvh5OqDUM9XqnJissGviiHX6PJuXSTgevENebhyF5CLhfDTz2oIQFmEVxTlPGvz8fUrFomncBjYiUT4gvJnfW6LrEI86r9rNOR/XqqbQ90lDNTUsSUXOOqClAoB71Y3TA1gpBSMm7DIwfJj9ULACw3RPMi9iADX6+pXY6pKKm65uMfEr0Zm8c3D22r7W9QoNceVw/C0nagCc8i2IxLUqMdMEGyZNy3SD+aV1FpI+2nc7OfQH2F5tl2arQcBB5SSoU6lC7Kf2pbL5B5e76AUSk4WKErwpgEhVfiNMxdE+8bycVjajBL0l+eHoFWBDg2pj+I2bPLZ89sa+ho8pHSjXS5yuCR4yD9AT3AmI4PjwyXXpivzbO2yweVOhafA+65sUc9Ugs3aVBgNq1FlFa22GH6ptapA72/y7bFfLpBbJp5L2HgDyWuedwrHPnUZ570zg1JUO6vU7AEHVhHJItxiKeIdSVLwsZtIvHfEdoftMu9lZwUl02e/2G4XroTbjcuJlgM1t9w7gzNItzvn19vhKEZBNqsUmJeNL5HzYvqAGaDrrdFWZ9jkKFlYKnzvQ7VdTiGSqWWhrqoFduto8rqCwFuQAelFSW2P+G3Z4WKg63s2
    STRIPE_API_KEY: AgB6yLa9qPtxHLRA9VdjSxuISsvxfJx6CDiWqnRSzk5Mz7hdEvLvVVUqh9IVHJU/l830WDUatq0qjBm3rHLaSr0s46oFrJeUQKNtUmegrj2lfqrMEELBy1BV3i+NDuHEYMdKs8+G4H9FNkTvyksds7ugHJ7pKoULKSd8q+jk+GYrNlzYhTArsQXF3w8qcfi+OA2TuFLyYPTHUkJCu1AMsvHY2iXTAzMS9u2iktze3PKpFWRcNcKeLMSej884ndGd2VfG1Xg1o5n3YHXW2QgcJ0+woAFYl+LLqbHNRLsRc6mZhkXAT383gTKJydsZQEfPbla1UNJ5iN+nLTzMygkFXOOBfv+3+v7t/2Lg5J+CZ1uC+8dTbt8oZRhTfcwSk9teLhydT8i4dQ/faNPXqwVvmmbznoCSlaO6uTxVL3SZyYYnMT7nlQxjjgYQCIT0m0LxHxAieMc6yVpxIk8AeNKCVXOcKLzk13yCQUiPWmMoaNQ70yKy9qFR1P7P5qvil0Dv/KhDPbTBcoapage0q7dse9Y+CQI8dAGOjWwZZxISt7hpdB4a3Y10DGE7H7hUfQkn3anVmpv07vKg4kN6oDUzeZdoELhpjJG00lokrplDT8GpKmGZ2inq0Wk4qLFgFCZQMP82juHHmliaTfMgyqrotPi8FKKMuUCjk3JhZAKQ8K9oq8UoV56br9y/7J1ELVj2dQVogdhyL2cGSA==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
