---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secret
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgBmA/low6OEE3yy4q/Qu7Fw3F5fVDMahKqozzGSR4b/1WyDqCZUjeIN9OVKleTRDIRjhZgnGXwJRg1Q+QXtoNRdVWSqTj5s1e8xGt4YrN9d79lx5e5bMAZWrCNnoQw6gnRjgduCaMt/jXAmfpHYNGUS99lM7M4yMF/OQ2/HdsECIwI7BznE6AWxhWWOi+DUKl3wcFTyM1yaYZwCOBjCCGGPB31y+QGCxIDEkMCHsHJwFq+cOio9cQyBRQ+UuFTUro6J/PD602jXqWbPh/JaFTSfLHaimCi5wBWFwfztsOtqAlcY1yPYUGqW7w9dI6Dt1kqCkaxzmnht4sWrOKIgFC595MPCSs2ff/6akrkSSZvGbQcffF7UCEdFgwnxfZtnp+l0Ei26uMJ3E2yRxK6K0/qaUQC8SceaDRnzsDvRhQAOrvmv4kpW1ZRbs/aTWOVcT3L3U8zjxSUsNixpU3TxOzrnSGDd7KKSonhg+CNqR7Byu7c1EQUjm6Mu11DtE6D22roOo8aSGMfNw+hPrR4GOiAiDp8uuMj2r5SmmUSagI7zT9pHQq5FPVodf9YUmFaOfyP11beqVQAY5rY+qiEaElWAuKCyWm7k487YvG0CQzOYaitBLhvyPs6JIDESD1UcCtxwDcAl/f4EGR+McVJRMbqMu0mh1xosuyZstcfAzZGEJndoRZcSmv7eo8DgA/ZH/pcoG94M8pAE7pFD763j
    STRIPE_API_KEY: AgCNejT0qVoj7qvf3lFRz0kXFp4hQyDebTvu73NksjodDokfWsVGDg6UJQgXObyyZZkJk3JI0B2qx9Nko21TFHYg+dSPhk03t4O/sp6TshxMsj3CbQUJtpXtGEiCHuQYw4hH8iozlZ/ijCSAj1cYdtMMPSX1igNX7IPLEqcpM6uagRMgB/pgfWkJ0CTfLvD4+obhY6CWOdIYA8ZKUfY3Oq8lLlqxw90PDipTCiJuAi0TqDvDrwE0sE9UjzIvetEQq936j4VhGUvVG01T0jTESL5KsmMrL2hApSMz8kdOYg3LJ5Un5CM3ma1Zkc3i3zSrVCsoexN+K6HICXJszJBYyZU5m97LeExfpy5WS4ztsKjqMDh9/dFiCadeXJ1U+Qqw1CzI27Je5GoQwFZylfBPcDw2l/BiiWFoGFmBdU/HQx/GRyAbKhYJlXumH4LsJ2wspySlGTRn4xSIw1TzuLAiQxAjSMrVDNZ0iC6Xxj1R3CPQVpT594Inmwhr2pUq8CtR9WHu9dxZv2Xhs8xiRhUBnOtuNiWvu9++nwl3xTlg4PeoYs791bNxsZtKvqP/nxFIPtK9UXJFiS6FpYkDUMYIcHK0zz8EzcMkauWGfy92ykNYr3vntFjTyw4wzloFS+E5ALToUvcmQVTGmBtImXhMlUM8lCAFGbnmWQn5bth3Itnk/N1I/d+z0yY2yhMRNeenfvsIs30Z4OKMUg==
  template:
    metadata:
      name: ledger-api-secret
      namespace: payments
