name: DevSecOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python Dependencies
        run: |
          pip install -r app/requirements.txt
          pip install bandit semgrep

      - name: Run Bandit
        run: |
          bandit -r app

      - name: Run Semgrep
        run: |
          semgrep scan \
            --config=auto \
            app/

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Build Docker Image
        run: |
          docker build -t ledger-api:scan ./app

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ledger-api:scan
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1
